# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "db" do |db|
      db.vm.box = "bento/ubuntu-22.04"
      db.vm.hostname = "db"
      db.vm.network :private_network, ip: "192.168.100.12"
      db.vm.provider "virtualbox" do |v|
        v.name = "db"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      
    end

end
